spring.application.name=evalspring
spring.datasource.url=jdbc:mysql://localhost:3306/evalspringDB
spring.datasource.username=root
spring.datasource.password=siixo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver